In [ ]:
'''
A와 B가 가위바위보를 하였다.

가위는 1, 바위는 2, 보는 3으로 표현되며 A와 B가 무엇을 냈는지 입력으로 주어진다.

A와 B중에 누가 이겼는지 판별해보자. 단, 비기는 경우는 없다.

 

[입력]

입력으로 A와 B가 무엇을 냈는지 빈 칸을 사이로 주어진다.

 
 

[출력]

A가 이기면 A, B가 이기면 B를 출력한다.

'''

In [ ]:
A, B = list(map(int, input().split()))


if A + B == 3:
  if A > B:
    print('A')
  else:
    print('B')

elif A + B == 4:
  if A > B:
    print('B')
  else:
    print('A')
elif A + B == 5:
  if A > B:
    print('A')
  else:
    print('B')

1 3
A

In [ ]:
'''
1부터 주어진 횟수까지 2를 곱한 값(들)을 출력하시오.

주어질 숫자는 30을 넘지 않는다.
'''

In [ ]:
T = int(input())
for i in range(0,T+1):
  print(2**i, end=' ')

8
1 2 4 8 16 32 64 128 256

In [ ]:
'''
주어진 숫자부터 0까지 순서대로 찍어보세요

아래는 입력된 숫자가 N일 때 거꾸로 출력하는 예시입니다
'''

In [ ]:
T = int(input())
for i in range(T, -1, -1):
  print(i, end=' ')

8
8 7 6 5 4 3 2 1 0

In [ ]:
'''
숫자 N은 아래와 같다.

N=2a x 3b x 5c x 7d x 11e

N이 주어질 때 a, b, c, d, e 를 출력하라.
'''

In [25]:
T = int(input())

for test_case in range(1, T+1):
  N = int(input())
  prime_numbers =[2,3,5,7,11] #소수 리스트 생성
  s_list = [] # while문을 돌며 소인수분해 값을 저장할 리스트 생성 
  while N != 1:
    for i in prime_numbers:
      if N % i == 0: 
        s_list.append(i)
        N = N / i

  pf_list = list(s_list.count(i) for i in prime_numbers) # s_list 안에 있는 각 소수의 갯수를 카운트해서 최종 값을 출력할 리스트에 저장

  print(f'#{test_case}', end = ' ')
  for k in pf_list:
    print(k, end = ' ')
  print()

3
100
#1 2 0 2 0 0
220
#2 2 0 1 0 1
300
#3 2 1 2 0 0